<?php
    return[
        'Mantenimiento/InicioCorrectivos' => 'Views/Templates/Mantenimiento/Correctivos/InicioCorrectivo.php',
        'Mantenimiento/Inicio' => 'Views/Templates/Mantenimiento/Inicio.php',
        'Mantenimiento/InicioPreventivos' => 'Views/Templates/Mantenimiento/Preventivos/InicioPreventivos.php',
        'Mantenimiento/InicioPasillo' => 'Views/Templates/Mantenimiento/Preventivos/InicioPasillo.php',
        'Mantenimiento/InicioManlift' => 'Views/Templates/Mantenimiento/Preventivos/InicioManlift.php',
        'Mantenimiento/InicioCombustion' => 'Views/Templates/Mantenimiento/Preventivos/InicioCombustion.php',
        'Mantenimiento/FirmaMantenimiento' => 'Views/Templates/Mantenimiento/Preventivos/FirmaMantenimiento.php',
        'Mantenimiento/FirmaOperario' => 'Views/Templates/Mantenimiento/Preventivos/FirmaOperario.php',
        'Mantenimiento/FirmaSupervisor' => 'Views/Templates/Mantenimiento/Preventivos/FirmaSupervisor.php',
        'Mantenimiento/FirmaMantenimientoC' => 'Views/Templates/Mantenimiento/Correctivos/FirmaMantenimientoC.php',
        'Mantenimiento/FirmaOperarioC' => 'Views/Templates/Mantenimiento/Correctivos/FirmaOperarioC.php',
        'Mantenimiento/FirmaSupervisorC' => 'Views/Templates/Mantenimiento/Correctivos/FirmaSupervisorC.php',
        'Mantenimiento/VerMantenimientoCorrectivo' => 'Views/Templates/Mantenimiento/Correctivos/VerMantenimientoCorrectivo.php',
        'Mantenimiento/Preventivo' => 'Views/Templates/Mantenimiento/Preventivos/Preventivo.php',
        'Mantenimiento/VerMantenimientoP' => 'Views/Templates/Mantenimiento/Preventivos/VerMantenimientoP.php',
        'Mantenimiento/VerMantenimientoPasillo' => 'Views/Templates/Mantenimiento/Preventivos/VerMantenimientoPasillo.php',
        'Mantenimiento/VerMantenimientoCombustion' => 'Views/Templates/Mantenimiento/Preventivos/VerMantenimientoCombustion.php',
        'Mantenimiento/VerMantenimientoManlift' => 'Views/Templates/Mantenimiento/Preventivos/VerMantenimientoManlift.php',
        'Mantenimiento/TraerAreas' => 'Views/Templates/Mantenimiento/Preventivos/TraerAreas.php',
        'Mantenimiento/TraerMontacargas' => 'Views/Templates/Mantenimiento/Preventivos/TraerMontacargas.php',
        'Mantenimiento/TraerOperarios' => 'Views/Templates/Mantenimiento/Preventivos/TraerOperarios.php',
        'Mantenimiento/BuscarTecnico' => 'Views/Templates/Mantenimiento/Preventivos/BuscarTecnico.php',
    ];
?>