<?php
    return[
        'Productos/Ver' => 'Views/Templates/Productos/Insumos/Ver.php',
        'Productos/Diseno' => 'Views/Templates/Productos/Insumos/Diseño.php',
        'Productos/CodigoBarras' => 'Views/Templates/Productos/Insumos/CodigoBarras.php',
        'Productos/Entrada' => 'Views/Templates/Productos/Entradas/Entrada.php',
        'Productos/InicioEntrada' => 'Views/Templates/Productos/Entradas/InicioEntrada.php',
        'Productos/InicioEntradaSedes' => 'Views/Templates/Productos/Entradas/InicioEntradaSedes.php',
        'Productos/FirmaEntrada' => 'Views/Templates/Productos/Entradas/FirmaEntrada.php',
        'Productos/FirmaSupervisor' => 'Views/Templates/Productos/Entradas/FirmaSupervisor.php',
        'Productos/VerEntrada' => 'Views/Templates/Productos/Entradas/VerEntrada.php',
        'Productos/EditarEntrada' => 'Views/Templates/Productos/Entradas/EditarEntrada.php',
        'Productos/AnularEntrada' => 'Views/Templates/Productos/Entradas/AnularEntrada.php',
        'Productos/Traslados' => 'Views/Templates/Productos/Traslados/Traslados.php',
        'Productos/InicioTraslados' => 'Views/Templates/Productos/Traslados/InicioTraslados.php',
        'Productos/InicioTrasladosSedes' => 'Views/Templates/Productos/Traslados/InicioTrasladosSedes.php',
        'Productos/FirmaTraslado' => 'Views/Templates/Productos/Traslados/Firma.php',
        'Productos/FirmaRecibe' => 'Views/Templates/Productos/Traslados/FirmaRecibe.php',
        'Productos/VerTraslado' => 'Views/Templates/Productos/Traslados/VerTraslado.php',
        'Productos/Salida' => 'Views/Templates/Productos/Salidas/Salida.php',
        'Productos/InicioSalida' => 'Views/Templates/Productos/Salidas/InicioSalida.php',
        'Productos/InicioSalidaSedes' => 'Views/Templates/Productos/Salidas/InicioSalidaSedes.php',
        'Productos/VerSalida' => 'Views/Templates/Productos/Salidas/VerSalida.php',
        'Productos/FirmaSalida' => 'Views/Templates/Productos/Salidas/FirmaSalida.php',
        'Productos/FirmaSalidaReceptor' => 'Views/Templates/Productos/Salidas/FirmaSalidaReceptor.php',
        'Productos/FirmaSupervisorSalida' => 'Views/Templates/Productos/Salidas/FirmaSupervisorSalida.php',
        'Productos/Ajuste' => 'Views/Templates/Productos/Ajuste.php',
        'Productos/Categorias' => 'Views/Templates/Productos/Categorias.php',
        'Productos/Inicio' => 'Views/Templates/Productos/Inicio.php',
        'Productos/InicioCantidadTotal' => 'Views/Templates/Productos/InicioCantidadTotal.php',
        'Productos/InicioInventarioTotal' => 'Views/Templates/Productos/InicioInventarioTotal.php',
        'Productos/TraerSubcategorias' => 'Views/Templates/Productos/TraerSubcategorias.php',
    ];
?>